### PR TITLE
Small Bug fixes

### PR DESCRIPTION
**Pull request by iOiurson**
This PR includes:
- Admin UI fixes
- use of  `node` instead of `nodemon`
- fix of empty HTML response reception

### CODE REVIEW

**Comment by vallettea** [comment]
so basically you just renamed sim on the interface but did no other change ?

**Comment by iOiurson** [comment]
With regards to that specific commit, yes.

**Comment by vallettea** [comment]
ok should I merge?

**Comment by iOiurson** [comment]
You should ^^

**Pull request merged**
