### PR TITLE
MQTT protocol

### PR DESCRIPTION
**Pull request by iOiurson**

### CODE REVIEW

**Comment by iOiurson** [comment]
MQTT now totally supersedes former TCP protocol.

## Elements
The new communication protocol is composed of 3 elements:
**broker**: authenticates clients and relays messages
**sensor** client
**maestro** client, on the kerrigan server

## Available Topics up to now:
*From* **sensor** *to* **maestro**:
- `init/mySensorSimId`, when sensor needs to initialize. There is no content.
- `status/mySensorSimId/type`, when a sensor status updates. The content is the actual status.
- `measurement/mySensorSimId/type`, when a measurement is sent from sensor. The content is an array of measurements.

*From* **maestro** *to* **sensor**:
- `mySensorSimId`, when maestro sends command to sensor. The content is a string of the command.
- `all`, when maestro sends command to all registered sensors. The content is a string of the command.

## Tests
19 tests are available.

### Database
12 tests from previous PR.

1) Place creation
2) Place update
3) Place deletion
4) All place deletion
5) Place get
6) All place get

7) Place creation
8) Place update
9) Place deletion
10) All place deletion
11) Place get
12) All place get

### Broker
13) Broker should not authenticate sensor with fake token

### Maestro utils
`checkSensor` and  `importSensor` are utility functions of maestro. `checkSensor` checks if the sensor that sent a message is known in the maestro sensor cache. `importSensor` imports all sensors from database to maestro sensor cache.

14) `checkSensor` should register unknown sensor
15) `checkSensor` should not register known sensor
16) `importSensor` should return an object with all sensors in DB

### Maestro
Tests to verify complete maestro functionality, from sensor message to maestro response.

17) Maestro should register unknown sensor
18) Maestro should send back init command when asked
19) Pushing wifi measurements

**Comment by iOiurson** [comment]
Actually, the tests 17 and 19 are not valid, they always pass no matter the values tested...
This is most probably due to the `setTimeout` that is used for these 2 tests. I'm working on it.

**Comment by vallettea** [comment]
Ok we are going to review all this with max.
What is the satus ?

**Comment by vallettea** [comment]
for the schema from serge, dont add them to the repo but copy paste the svg to the drive and link it

**Comment by vallettea** [comment]
this is becoming to be neat ! I could present the architecture to max in less than 5mins
:clap:

**Pull request merged**
